### ISSUE TITLE
makeRelative never introduces "../"

### ISSUE THREAD

**Issue by mgsloan** [mrkkrp/path-io#10]
This is due to how the implementation in filepath works - https://hackage.haskell.org/package/filepath-1.4.1.0/docs/System-FilePath-Posix.html#v:makeRelative .  While somewhat "correct" to never yield "../", I find that behavior fairly useless.  We should choose the behavior that will reduce unexpected errorcases in user code.  If `..` does go up a directory, then it should be used.  Otherwise throw some error like "Couldn't make /some/abs/path relative /a/wonky/path because they don't straightforwardly share an ancestor"

**Comment by mrkkrp** [comment]
AFAIK, it's not possible to construct a `Path` with `..` segment in it anyway, see: https://github.com/chrisdone/path/pull/8. For example:

```
λ> parseRelFile "../something.txt"
*** Exception: InvalidRelFile "../something.txt"
```
