### ISSUE TITLE
resolveFile/Dir and tilde don't work well together

### ISSUE THREAD

**Issue by NorfairKing** [mrkkrp/path-io#14]
```
resolveFile' "~/file"
"/home/user/~/file"
```
Instead of:
```
resolveFile' "~/file"
"/home/user/file"
```

Is this intentional?

**Comment by mrkkrp** [comment]
Tilde is a shell feature, the functions are not supposed to resolve it.

**Comment by NorfairKing** [comment]
Hm you're right, that's annoying. Environment variables also don't get resolved.
That doesn't make for a nice user experience though. Is there a chance that you'll build a function that can offer these functionalities?

**Comment by mrkkrp** [comment]
I'm not sure this is in scope of the package.

**Comment by NorfairKing** [comment]
That's fair enough! Thank you for your time.
