### ISSUE TITLE
Import missing functions from stack’s Path.IO

### ISSUE THREAD

**Issue by cocreature** [mrkkrp/path-io#2]
Stack has a bunch of useful functions in [Path.IO](https://hackage.haskell.org/package/stack-1.0.2/docs/Path-IO.html).
In particular the `resolve` family of functions and `parseRelAbs` functions are useful so it would be nice to add them. Ideally stack would switch to just depending on this but I am not sure if you have already talked to them about it and what their opinion is on this.

**Comment by mrkkrp** [comment]
I'll see what is still missing and then I'll propose Stack's maintainers to use the library. I haven't talked to them yet.

**Comment by cocreature** [comment]
Thanks for the quick answer!

**Comment by mrkkrp** [comment]
I've talked to Stack maintainers and there will be switch I guess. About `parseRelAbs`, this is already is `path-io`, see [here](https://github.com/mrkkrp/path-io/blob/master/Path/IO.hs#L533) how I've handled it, `makeAbsolute` works with files and directories.

Functions that I'll add soon:

* `resolve` (probably one function will handle everything)
* `…IfExists` family of functions. Not sure about this. I'll see how intensively the functions are used in Stack source and then decide.

…Or even better, actually. With these paths it's possible to write higher-order helper that will perform given action on object only if it exists. Much more elegant than having a bunch of functions with `IfExists` suffix. That's the way, I think.

**Comment by mrkkrp** [comment]
Added `forgivingAbsence` helper, `resolveFile`, and `resolveDir` (I decided it's better to have two versions because otherwise polymorphism on result type will be needed and it's kinda awkward and an unnecessary complication in genepal). Now `path-io` has everything from Stack's `Path.IO`.

**Comment by cocreature** [comment]
Thanks!

**Comment by mrkkrp** [comment]
I'll release new version when I'm done with a PR that makes Stack do all its file operations via this library. That will be a good test for the package. Right now I see that some functions are still missing, for example `makeRelative` and `makeRelativeToCurrentDir`.
