### ISSUE TITLE
Unify MonadIO and MonadThrow constraints?

### ISSUE THREAD

**Issue by snoyberg** [mrkkrp/path-io#27]
A number of functions provide both `MonadIO` and `MonadThrow` constraints. However, by sticking a `liftIO` in front of the function body, we can knock this down to just a `MonadIO` constraint in all cases. Is there any objection to this change? If not, I can send a PR.

**Comment by mrkkrp** [comment]
I think this is actually a good idea, please go ahead with the PR. I wonder if the same can be done about `MonadCatch`. I'd start by moving `ignoringIOErrors` (internal helper) into plain `IO` and then adding `liftIO` in front of `copyDirRecurGen` and similar, the constraint should go away then, although maybe I'm missing something.

We could try to stop depending on `exceptions` directly then. `path` still depends on `exceptions` though.

**Comment by snoyberg** [comment]
PR #28 is open.
