### ISSUE TITLE
resolveDir doesn't take in account substituted paths on Windows

### ISSUE THREAD

**Issue by varosi** [mrkkrp/path-io#30]
Example:

In Windows cmd:

> subst P: D:\Work\long\builder\jenkins\home\workspace\test_master-IH6I4ZJQUG22JDFTMS624VMTMO5APB7UUFMDD7ZRLLQLR32Y2H5A\test
> P:

then in GHCi:

> Prelude> x <- getCurrentDir
> Prelude> x
> "P:\\test\\"
> Prelude> resolveDir x "."
> "D:\\Work\\long\\builder\\jenkins\\home\\workspace\\test_master-IH6I4ZJQUG22JDFTMS624VMTMO5APB7UUFMDD7ZRLLQLR32Y2H5A\\test\\test\\"

This is not correct and rises this problem https://github.com/commercialhaskell/stack/issues/3442 in Stack tool.
It should resolve to substituted drive like that:

> Prelude> resolveDir x "."
> "P:\\test\\"

For Windows and tools this is transparent and they treat P: as a separate drive.

**Comment by mrkkrp** [comment]
Any idea how to fix this? Right now the definition looks like this:

```haskell
resolveDir b p = liftIO $ D.canonicalizePath (toFilePath b F.</> p) >>= parseAbsDir
```

I guess it's a problem with `canonicalizePath` from `directory` then?

**Comment by varosi** [comment]
hm, yes, the problem is there indeed. I'll check with directory module.

**Comment by varosi** [comment]
Canonical paths may be used for paths equallity. But may be we have to differentiate "absolute" from "canonical" paths. Canonical paths should be like those returned from canonicalizePath function. Absolute paths (at least under Windows) should preserve drive letter. 

Here is some more information about the case:
http://pdh11.blogspot.bg/2009/05/pathcanonicalize-versus-what-it-says-on.html

**Comment by mrkkrp** [comment]
Should we close this one?
