### ISSUE TITLE
walkDir has a potential for non-determinism

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/path-io#36]
Since `listDir` returns entries without any defined order and the `MaybeT` moned transformer will shortcut once it sees first `Nothing`, the action `walkDir` is not quite deterministic.

CC @harendra-kumar

**Comment by mrkkrp** [comment]
`listDirectory` and `getDirectoryContents` do not sort directories and do not give any guarantees about the ordering. I guess the ordering is deterministic but it may be different when we perform the action in e.g. different copies of the same tree.

**Comment by harendra-kumar** [comment]
The directory listing APIs would ultimately call `readdir` (on POSIX). `readdir` would return directory entries in a filesystem specific order, generally in whatever order the filesystem stored them. However, unless the directory is modified between calls the order should remain the same for successive calls. So `walkDir` is as good as any other logic that would consume the output of `readdir`. It basically allows you to traverse the directory in the filesystem storage order and the traversal termination behavior depends on the user supplied handler. If there are any issues, they are between the user and the filesystem, `walkDir` is just a transparent broker between the two.

**Comment by mrkkrp** [comment]
> However, unless the directory is modified between calls

I mean to say that if I make a copy of a directory and then I walk the original and the copy, the results may be different, which may be unexpected.

**Comment by mrkkrp** [comment]
OK, let’s close then.
