### ISSUE TITLE
Confusing type and docs for `getAppUserDataDir`

### ISSUE THREAD

**Issue by sjakobi** [mrkkrp/path-io#4]
```haskell
getAppUserDataDir :: (MonadIO m, MonadThrow m)
  => Path Rel Dir      -- ^ A relative path that is appended to the path
  -> m (Path Abs Dir)
```
What I find confusing about this is that the first argument isn't really the last segment of the resulting path:

```
λ> getAppUserDataDir $(mkRelDir "my-app")
"/home/simon/.my-app/"
```
The last segment of the result (on UNIX systems) is `.my-app` instead. But supplying `$(mkRelDir ".my-app")` as argument to the call would be wrong of course.

I think using `String` instead of `Path Rel Dir` would make this clearer.

**Comment by sjakobi** [comment]
That was quick! :+1:

**Comment by mrkkrp** [comment]
Do you need this thing right now? I plan to write some tests before next release, but if you need the function with this new signature, I can release new version of the package without delay. BTW, feel free to report more of this stuff (although most functions should be sane).

**Comment by sjakobi** [comment]
> Do you need this thing right now?

No worries, it's not a bug, just something we'll need to adjust in `stack` at some point.
