### ISSUE TITLE
Move something like `AnyPath` to `path` package

### ISSUE THREAD

**Issue by mgsloan** [mrkkrp/path-io#5]
I'm thinking that this could be done instead of having `AnyPath` in path-io:

Add the following to `path`:

```haskell
class AnyPath a where
    parsePath :: MonadThrow m => String -> m a
```

Then:

```haskell
canonicalizePath :: AnyPath (Path r t)  => Path r t -> Path Abs t
makeRelative :: (AnyPath (Path r t), MonadThrow m) => Path Abs Dir -> Path r t -> Path Abs t
```
etc

**Comment by mrkkrp** [comment]
Well, these functions (`canonicalizePath` and `makeAbsolute`) need to be in `IO` (or `MonadIO` if we generalize), so your signatures are a bit incorrect. (`makeRelative` is added later for “completeness”.) My position here is that `path` is pure package providing core data types and operations on them, similar in its purpose to `filepath`. `path-io` on the other hand currently handles everything that has to do with IO (plus a little extra, like `makeRelative`). Following this logic I think it's better to keep `canonicalizePath` and `makeAbsolute` in `path-io` (note that `path` does not depend on `directory`, so why make it depend on it when `path-io` already handles this?).

I do think that `path` should be extended, but I would extend it to include more pure operations (functions to replace extension, etc.), so using `filepath` would become unnecessary.

**Comment by mgsloan** [comment]
Right, I think `canonicalizePath` and `makeRelative` (in path-io) can be defined in terms of the `parsePath` method.

**Comment by mrkkrp** [comment]
They can, but why this would be better than current implementation? Honestly, I don't like the idea of introducing polymorphic parser function, because well, people would be tempted to actually use it. As Chris pointed out in his [blog post announcing `path`](http://chrisdone.com/posts/path-package):

> It was discussed briefly whether we should just have a class for parsing rather than four separate parsing functions. In my experience so far, I have had type errors where I wrote something like `x <- parseAbsDir someAbsDirString` because `x` was then passed to a place that expected a relative directory. In this way, overloading the return value would’ve just been accepted. So I don’t think having a class is a good idea. Being explicit here doesn’t exactly waste our time, either.

**Comment by mgsloan** [comment]
Good point!  I suppose one option would be to have this class in `path-io`, but not export the method.  Seems fine either way, though.
