### ISSUE TITLE
Is there a `resolveFile{',}` function that doesn't follow up symlinks?

### ISSUE THREAD

**Issue by german1608** [mrkkrp/path-io#53]
I take input from the user to the path of where a symlink will be created. When the path does not exists, it construct the path fine, but when it exists and its a symlink, it resolves the target of the symlink.

I know that `resolveFile` uses `canonicalizePath` from `directory` package, but i'd like to know if there is a version of `resolveFile` that doesn't follow up symlinks.

Specifically, what I'd like to do is to check if the link exists and if so, delete it. But resolveFile returns the target, and that can't be deleted.

**Comment by mrkkrp** [comment]
You can always implement your own version of `resolveFile` that does exactly what you want. You can take the code from `path-io` as a starting point.

**Comment by german1608** [comment]
@mrkkrp thanks! Are you open to contributions? Maybe somebody can find that function useful in the future.

**Comment by mrkkrp** [comment]
Yes, having a different version of `resolveFile` seems to make sense in this case.

**Comment by german1608** [comment]
cool, I'll try to add it whenever I have time.
