### ISSUE TITLE
Space leak in `walkDirAccum` due to lazy `WriterT`

### ISSUE THREAD

**Issue by mrputty** [mrkkrp/path-io#55]
I am using `walkDirAccum` to traverse a large directory tree, but am seeing excessive memory consumption.  Upon profiling, this appears to be due to laziness in the writer used in `walkDirAccumWith`, which appears to be holding on to all the `Path` values it constructs.  Making my handler strict has no effect on this behavior.  As an experiment, I built `path-io` locally with `Control.Monad.Trans.Writer.Strict`, and this dramatically reduces the memory footprint.

Are there use cases that depend on a lazy writer?  Am I missing a way to make this strict without using a strict writer?

**Comment by mrkkrp** [comment]
@harendra-kumar Do you remember if there is a reason for using lazy writer? If no, let's just switch to the strict one.

**Comment by harendra-kumar** [comment]
I do not think there was a specific reason for that.

**Comment by mrkkrp** [comment]
@mrputty Would you be able to open a PR to fix this?

**Comment by mrputty** [comment]
Pull request #56 addresses this issue.

**Comment by mrkkrp** [comment]
I published version 1.6.1 with the fix.
