### ISSUE TITLE
`createFile` and `ensureFile`

### ISSUE THREAD

**Issue by StevenXL** [mrkkrp/path-io#58]
Hello - thank you for such a nice library. Given the existing of [createDir](https://github.com/mrkkrp/path-io/blob/0d20b320f7885bad6c3ac948a3549d645f224c9a/Path/IO.hs#L174) and [ensureDir](https://github.com/mrkkrp/path-io/blob/0d20b320f7885bad6c3ac948a3549d645f224c9a/Path/IO.hs#L195), I was wondering if a `createFile` and `ensureFile`(?) should exist.

**Comment by mrkkrp** [comment]
Should these functions create empty files?

**Comment by StevenXL** [comment]
@mrkkrp I thought I had a use-case for this (which would have helped me answer your question), but whatever that use case was is now gone. If I run into it again, I might re-open the issue (if you don't mind). For now, I will close. Thanks for the response.
