### ISSUE TITLE
removeDirLink fails in Linux

### ISSUE THREAD

**Issue by ivo-stefchev** [mrkkrp/path-io#59]
The way this is implemented `removeDirLink = liftD FilePath -> IO ()
D.removeDirectoryLink` will not work, because *directory* package removeDirectoryLink expects the symlink to be supplied without trailing slash.

**Comment by mrkkrp** [comment]
Do you want to open a PR to fix this?

**Comment by ivo-stefchev** [comment]
yes

**Comment by mrkkrp** [comment]
@ivo-stefchev Do you want a release with the fix?

**Comment by ivo-stefchev** [comment]
I can wait until next regular release of path-io, so not immediately.
I currently use directly *directory* package to remove symlinks of dirs.
