### ISSUE TITLE
Support path 0.9

### ISSUE THREAD

**Issue by brandonchinn178** [mrkkrp/path-io#62]
This is blocking getting `path` and `path-io` back into Stackage nightly (`path-0.8` required `template-haskell < 2.17`, which GHC 9 breaks)

https://github.com/commercialhaskell/stackage/blob/a8afb6a22d582763e6f486300a95e3c27faeda33/build-constraints.yaml#L5488

**Comment by mrkkrp** [comment]
I also published a revision on Hackage that adjusts the bounds.
