### ISSUE TITLE
Feature request: Add `getFileSize` function

### ISSUE THREAD

**Issue by bitc** [mrkkrp/path-io#67]
The [getFileSize](https://hackage.haskell.org/package/directory-1.3.7.0/docs/System-Directory.html#v:getFileSize) function should be added.

Thought: The original function from `System.Directory` returns an `Integer`. I am not sure what the attitude is for this library regarding changes to the wrapped functions, but I for what it's worth, I personally think it would be better to return an `Int64`

**Comment by bitc** [comment]
> > I personally think it would be better to return an Int64
> 
> Can you motivate this change?

  - `Int64` is much faster than `Integer`
  - It is easier and more intuitive how to do binary serialization of `Int64` and how to store in a database
  - The system calls that return a file size don't actually return an unbounded integer, but rather (on pretty much all platforms) return something much closer to `Int64`
  - Lots of other Haskell libraries have adopted `Int64` for things representing filesizes. Examples:
    - [binary](https://hackage.haskell.org/package/binary): [`bytesRead :: Get Int64`](https://hackage.haskell.org/package/binary-0.8.9.0/docs/Data-Binary-Get.html#v:bytesRead)
    - [tar](https://hackage.haskell.org/package/tar): [`type FileSize = Int64`](https://hackage.haskell.org/package/tar-0.5.1.1/docs/Codec-Archive-Tar-Entry.html#t:FileSize)

But at the end of the day this isn't all that important to me. There are benefits to being consistent with `System.Directory` and it is trivial to `fromInteger` the result if needed

**Comment by mrkkrp** [comment]
This is now on master. I'll publish 1.7.0 shortly.
